from os import PathLike
from typing import Optional, Union

StrPath = Union[str, PathLike[str]]

__version__: str

class AegisError(Exception): ...
class Shredded(AegisError): ...
class UnknownKey(AegisError): ...
class WrongMasterKey(AegisError): ...
class IntegrityError(AegisError): ...
class UnsupportedFormat(AegisError): ...
class KeystoreError(AegisError): ...

class MasterKey:
    @staticmethod
    def generate() -> MasterKey: ...
    @staticmethod
    def from_base64(encoded: str) -> MasterKey: ...
    @staticmethod
    def from_env(name: str = "AEGIS_MASTER_KEY") -> MasterKey: ...
    @staticmethod
    def from_file(path: StrPath) -> MasterKey: ...
    @staticmethod
    def from_passphrase(passphrase: str) -> MasterKey: ...
    def to_base64(self) -> str: ...
    @property
    def kind(self) -> str: ...

class ShredReceipt:
    @property
    def subject_hash(self) -> str: ...
    @property
    def key_id(self) -> str: ...
    @property
    def shredded_at(self) -> int: ...
    @property
    def audit_seq(self) -> int: ...

class AuditReport:
    @property
    def ok(self) -> bool: ...
    @property
    def entries(self) -> int: ...
    @property
    def head(self) -> str: ...
    @property
    def first_bad_seq(self) -> Optional[int]: ...

class Vault:
    @staticmethod
    def open(
        path: StrPath,
        master_key: MasterKey,
        *,
        create: bool = False,
        audit_data_access: bool = False,
    ) -> Vault: ...
    def seal(self, subject: str, data: bytes, context: Optional[bytes] = None) -> bytes: ...
    def unseal(self, sealed: bytes, context: Optional[bytes] = None) -> bytes: ...
    def seal_file(
        self, subject: str, source: StrPath, destination: StrPath, context: Optional[bytes] = None
    ) -> None: ...
    def unseal_file(self, source: StrPath, destination: StrPath, context: Optional[bytes] = None) -> None: ...
    def has_key(self, subject: str) -> bool: ...
    def shred(self, subject: str) -> Optional[ShredReceipt]: ...
    def verify_audit(self) -> AuditReport: ...
    def audit_head(self) -> tuple[int, str]: ...
    def rotate_master_key(self, new_master_key: MasterKey) -> None: ...
    def export_tombstones(self, path: StrPath) -> int: ...
    def import_tombstones(self, path: StrPath) -> int: ...

def run_cli(argv: list[str]) -> int: ...
